name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install Packages
      - name: Install Packages
        run: bun install

      # Run Lint
      - name: Run Lint
        run: bun run lint

      # Run Unit Tests
      - name: Run Unit Tests
        run: bun run test

      # Upload Coverage
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      # Copy Environment Variables
      - name: Copy Environment Variables
        run: cp .env.development .env

      # Build Package
      - name: Build Package
        run: bun run package

      # Upload Artifact - Web
      - name: Upload Artifact - Web
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      # Upload Artifact - Desktop
      - name: Upload Artifact - Desktop
        uses: actions/upload-artifact@v4
        with:
          name: desktop
          path: desktop
